AUTOGENERATED

<h1 id="-dream-cuisine-"><strong>🥂 Dream Cuisine 💤</strong></h1>
<p>#</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left"><em>Section Summary</em> Somnivores hunt by using their exceptional hearing abilities, following
        sounds associated with sleep. When a somnivore eats fresh dream essence, the dream’s contents play through their mind like
        a memory of their own. Hunting or harvesting dreams on Earth requires a special license. Dreamers are not able to remember
        any dreams that are eaten. If a dreamer has their dreams consumed too regularly, they will start to experience negative
        mental side effects. Dreaming residents of Reverie often opt-in to donating their dreams to be eaten on a select number of
        nights per month. Most somnivores rely on shelf-stable dream brews to meet their nutritional needs They can also cook with
        “essence concentrate” to incorporate dreams into other foods. It always tints the food with its potent coloration.
        Somnivores <em>can</em> eat things other than dreams, but they don’t provide any nutritional value unless they’re prepared
        with essence concentrate. Their favorite foods align with what real world bats eat! They like bugs, fish, fruits, berries,
        nuts, and flowers.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>#</p>
<h1 id="-eating-dreams-"><strong>Eating Dreams</strong></h1>
<h1 id="-">---</h1>
<h2 id="-traditional-hunting-"><strong>Traditional Hunting</strong></h2>
<p>Somnivores use their exceptional hearing abilities to find a dreamer by focusing on the sounds associated with sleep (i.e.
  snoring, deep breathing, sheets rustling). Once a somnivore has located their prey, they will settle around the dreamer in
  whatever manner suits it - some like to perch upon headboards, while others may lay on a dreamer’s chest. The somnivore then
  slowly absorbs the dream from their host, breathing in or munching on the pillowy dream essence and feeling the dream’s contents
  <strong>play through their mind</strong> like a distant memory of their own. As the dream is consumed, the somnivore’s wings and
  horns will subtly glow brighter with the new fuel.</p>
<h2 id="-impact-on-the-dreamer-"><strong>Impact on the Dreamer</strong></h2>
<p>The dreamer will not be able to recall their dream upon waking. This can be seen as a benefit to some and a loss to others,
  depending on the dream’s contents. Being unable to remember your dream is a common phenomenon; it could be because your dream
  became a somnivore’s meal. 🦇</p>
<p>There are no other <em>immediate</em> effects besides this small lapse in memory; however, if a person has their dreams eaten
  too regularly it may begin to take a toll on their mind. REM sleep is essential for memory, learning, and emotional processing.
  Without this crucial cognitive function, dreamers may experience the following symptoms after having their dreams consumed for
  several consecutive nights:</p>
<ul>
  <li>Brain Fog &amp; Memory Problems</li>
  <li>Increased Irritability</li>
  <li>Cognitive Impairment</li>
  <li>Auditory and Visual Hallucinations</li>
</ul>
<h1 id="-live-feeding-"><strong>Live Feeding</strong></h1>
<h1 id="-">---</h1>
<p>A fresh meal directly from the source is a delicacy for somnivores. Many rely heavily on the convenience of bottled dream
  brews, never actually needing to hunt for their sustenance.</p>
<h2 id="-feeding-in-reverie-"><strong>Feeding in Reverie</strong></h2>
<p>Dreaming residents of Reverie typically allow their dreams to be eaten - they can visit their local community center and fill
  out paperwork to be entered into the Registry of Dreamers. Enrollment rewards a monthly monetary compensation and can be opted
  out of at any time.</p>
<p>Registered dreamers are given a sticker to place on their bedroom window - if that window is left open, a somnivore is welcome
  to swoop inside and enjoy a fresh meal. Dreamers are encouraged to donate during 7 to 15 non-consecutive nights per month.</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image1]</th>
      <th style="text-align:left">Bunny I don’t really <em>care</em> about my follower count on Glimmr, but it’s definitely not
        without its perks! 👀 Sometimes dreamers even slide into my DMs to offer me their night’s meal in hopes that I’ll vlog
        about it! 💕 Hehe, the weirder or more exciting, the better! Nothing’s yummier a fresh dream 😋 And I’m super thankful
        that they give me so many fun stories to share!</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<h2 id="-hunting-on-earth-"><strong>Hunting on Earth</strong></h2>
<p>Hunting on Earth must be done with the utmost caution to avoid being caught. Somnivores that wish to feed fresh from humans or
  take up Dream Harvesting must pass an exam to become certified.
  The exam for a <strong>Dream Hunter’s License</strong> tests for:</p>
<ul>
  <li>Mastery of invisibility</li>
  <li>Flight maneuverability</li>
  <li>Portal Channeling</li>
</ul>
<p>##</p>
<h1 id="-processed-dreams-"><strong>Processed Dreams</strong></h1>
<h1 id="-">---</h1>
<h2 id="-dream-brews-"><strong>Dream Brews</strong></h2>
<p>Given that live feeding is not a consistently available option for somnivores in Reverie, dream brews are usually a somnivore’s
  go-to for fulfilling their daily dream intake. These bottled dreams have a much longer <strong>shelf life</strong> compared to
  fresh dream essence (which has virtually none). Unfortunately, the specific contents of the dreams fade away with age, leaving
  only their signature flavor and a gentle stir of emotion.</p>
<p>![][image2]</p>
<p>Dream brews often use special mana-infused ingredients to punch up their flavors or to maintain emotional potency for extended
  periods of time. It’s an art form that many somnivores are dedicated to. These specialty brews are often sold in their own
  custom glass vials - containers just as unique as the concoction inside.
  ![][image3]
  Artisan brews can be a bit pricey for everyday fare though, which is where <strong>mass-produced</strong> dream brews come in!
  These are typically contained in simple glass or plastic bottles adorned with flashy labels that advertise their “nutritional
  benefits”. The flavors aren’t nearly as nuanced as an artisan brew’s, but they get the job done.</p>
<p>R.E.M. is the largest company that mass produces these drinks thanks to their innovations in dream harvesting and processing
  technology. If you would like to see “how it’s made” be sure to schedule a tour of their factories in the Industrial District!
</p>
<p>##</p>
<h2 id="-essence-concentrates-"><strong>Essence Concentrates</strong></h2>
<p>Don’t feel like drinking your daily dreams? Try cooking with dream essence concentrate instead! These can be used to
  incorporate a somnivore’s nutritional needs into just about any kind of food - though it will end up tinting the cuisine with
  its potent coloration.</p>
<p>![][image4]</p>
<p>#</p>
<h1 id="-dream-collection-"><strong>Dream Collection</strong></h1>
<hr>
<h2 id="-dream-harvesting-"><strong>Dream Harvesting</strong></h2>
<p>Harvesters are vacuum-like machines used to collect and condense dream essence for later consumption.
  They intake clouds of dream essence and process them through a cooling chamber to condensate. This turns the gas into liquid,
  which can then be used for raw consumption, or for brewing dream potions.</p>
<p>Harvesters come in many shapes and sizes. The larger and more advanced models are used by professional Dream Collectors. They
  have the ability to sort dreams by type into separate chambers and have a large capacity.</p>
<p>Personal models are small and lightweight, typically only having one chamber. It’s ideal for taking a dream “to-go”.</p>
<p>![][image5]</p>
<p>##</p>
<h2 id="-sheep-sprites-"><strong>Sheep Sprites</strong></h2>
<p>The large majority of the dream essence in Reverie is collected by sheep sprites, a mystical species of lamb-like creatures who
  have been bred over centuries to harvest dream essence.</p>
<p>They operate similarly to bees that collect pollen - venturing out each night to search for dream essence, gathering it around
  their small bodies, and then returning to their pasture. Once home, the sheep sprites are sheared and the collected essence is
  delicately packaged and sent away for processing - otherwise, it would naturally dissipate.</p>
<p>The most well known sheep sprite farm is Starlit Acres, located in Dreamhaven!
  ![][image6]</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image7]</th>
      <th style="text-align:left">Millie Cas, Cas! What snack would your little sheepies like me to bring for them when I visit
        this weekend?</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image8]</th>
      <th style="text-align:left">Caspian … ... Pixiefluff. And a slice of your heart drop cake. … For the sheep.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>#</p>
<h1 id="-other-foods-their-industries-"><strong>Other Foods &amp; Their Industries</strong></h1>
<hr>
<p>Somnivores also enjoy eating foods outside of dream essence - it lets them experience different textures and flavors they don’t
  traditionally get from downing their daily dream brew. However, non-dream foods are purely a creature comfort and don’t provide
  any nutritional value (unless they’re prepared with essence concentrate).</p>
<p>Somnivores’ favorite foods align with those of real world bats:</p>
<ul>
  <li>Bugs &amp; Fish</li>
  <li>Fruits &amp; Berries</li>
  <li>Nuts &amp; Seeds</li>
  <li>Flowers &amp; Nectar</li>
</ul>
<p>![][image9]</p>
<p>The industries that provide these foods are relatively small, existing only for somnivores’ culinary enrichment and Reverie’s
  non-somnivore population.</p>
<p>Any produce that can be grown and cared for in large quantities like this would not offer any significant magical properties
  like their wild-grown counterparts. Regardless, these blooms, berries, and bugs will surely have you coming back for seconds!
</p>
<h2 id="-horticulture-"><strong>Horticulture</strong></h2>
<p>Horticulture farms cultivate various plant-based foods for consumption. Primary crops include vegetables, fruits, nuts, and
  berries.</p>
<ul>
  <li>Harvest Moons Farm - Located in Dream Haven</li>
</ul>
<h2 id="-floriculture-"><strong>Floriculture</strong></h2>
<p>Floriculture hubs focus on growing edible flowers with enhanced size, texture, and flavor. Nectar is also collected and sold at
  high prices.</p>
<ul>
  <li>Mellow Meadows - Located in Dream Haven</li>
</ul>
<h2 id="-insect-husbandry-"><strong>Insect Husbandry</strong></h2>
<p>This husbandry involves raising and caring for different kinds of insects to increase their meatiness, juiciness, and/or
  crunchiness.</p>
<ul>
  <li>The Grub Bubs - Located in Grimhallow</li>
</ul>
<h2 id="-aquaculture-"><strong>Aquaculture</strong></h2>
<p>A small industry that provides Reverie with fresh fish, crustaceans, and some aquatic plants.</p>
<ul>
  <li>Eventide Fishery - Located in Lullabay</li>
</ul>
<h2 id="-earth-imports-"><strong>Earth Imports</strong></h2>
<p>For any produce needs that can’t be met by Reverie’s farms or environment, there’s always the option to import from Earth.
  Witches facilitate these exchanges, trading bulk goods from human society in exchange for magic plants and artifacts from
  Reverie; the exchange rate is quite good, since Earth produce is much more abundant in comparison.</p>
