AUTOGENERATED

<h1 id="-somnivore-origins-"><strong>🌙 Somnivore Origins 🔮</strong></h1>
<h2 id="-how-these-curious-little-dream-eaters-came-into-being-"><em>How these curious little dream eaters came into being</em></h2>
<p>#</p>
<table>
<thead>
<tr>
<th style="text-align:left"><em>Section Summary</em>  Monsters that need to harm humans to sustain themselves began to struggle and die off in the modern age as human society became more sophisticated. Includes vampires, succubi, and other demons and ghouls.  The Infernal Alliance was formed as a desperate attempt to find strength in numbers. Experiments were conducted using their combined magics, eventually leading to the creation of a new creature; the Somnivore.  Somnivores’ ability to feed on dreams without the need to harm their prey would allow their demonic heritage to live on and prosper, even in modern times. Reverie is a new realm that somnivores created. It lies parallel to Earth, providing ample space for their species to grow while maintaining easy access to their food source.</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left"></td>
</tr>
</tbody>
</table>
<p>#</p>
<h1 id="-the-end-of-an-era-"><strong>The End of an Era</strong></h1>
<h1 id="-">---</h1>
<p>As long as there have been humans, there have been monsters in the dark to feast on them. Blood, sex, souls…. All fuel for another’s being. Not a drop of human vitality was spared from those who lived in shadows. But the advancement of civilization brought with it new….complications. The humans were everywhere, their eyes and ears constantly on alert for what once went bump in the night. Suddenly, killing too many humans would quickly reverse the role of hunter and prey. Many monsters needed to adapt to exist more quietly beside humankind - some even forged symbiotic relationships, while others opted for disappearing off the radar completely.</p>
<p>#</p>
<h1 id="-the-infernal-alliance-"><strong>The Infernal Alliance</strong></h1>
<hr>
<p>In the early 16th century, the desperate and forsaken creatures left to starve in this changing world decided to take drastic action. Monsters who once fought over territory and petty squabbles alike were now forced into an accord. Ancient feuds were laid down in order to work together to combat the rapidly progressing and expanding human population. Any creature that could not cooperate with this new alliance would see their own populations fade into extinction.</p>
<p>Those who survived knew they could never again outpace humanity. The only option to save the Alliance’s dwindling kin was to move their society somewhere else altogether. Deep beneath the earth, a town was erected atop a massive stone pillar protected both by an equally enormous cavern and powerful illusory magic. It was given the name the <strong>Obsidian Nest</strong>. As a failsafe, a runic teleportation glyph was set into the very cobbles of the town. With its power, the entirety of their new haven could be quickly transported to another realm if ever they were discovered.</p>
<p>#</p>
<h1 id="-the-soul-prism-experiments-"><strong>The Soul Prism Experiments</strong></h1>
<hr>
<p>Within this shared refuge, the alliance pooled their magical acumen and resources together. Their most significant discovery was the <strong>soul prism,</strong> a volatile and potent material smuggled from the Underworld. These crystalline shards contained pieces of fractured souls, and contained the potential to forge new life.</p>
<p>![][image1]</p>
<p>The alliance saw soul prisms as the key to their salvation: if monsters could no longer safely consume humanity in the old ways, they would create a new kind of creature that could thrive unseen among them.</p>
<p>Many of the experiments failed, creating abomination after abomination. They gave life to fleshy globs and hollow hybrid beasts, twisted unpleasantly by unrefined overlapping magics. However, over time, a stable fusion emerged— the <strong>somnivore</strong>.</p>
<p>![][image2]</p>
<p>#</p>
<h1 id="-the-birth-of-somnivores-"><strong>The Birth of Somnivores</strong></h1>
<hr>
<p>Forged through the Soul Prism Experiments, somnivores were the amalgamation of vampire bloodlines, the dream-walking essence of succubi, and a concoction of other demons and lesser imps. It was a lengthy and arduous process in the beginning, but those who survived were surprisingly stable and held promise to become the true descendant of the struggling night creatures.</p>
<p>Somnivores’ complex heritage allowed them to feed on dreams without harming the host, leaving their prey with only a vague sense of forgetfulness upon waking. In addition, the dreams they fed on provided them with fuel for a diverse and powerful toolkit of magical abilities, pulling energy from raw imagination.</p>
<p>Somnivores were strong, yet harmless - not unlike a venomous spider with fangs too small to break skin. It’s this exact breed of duality that would allow a creature of the shadows to thrive in the modern age. Not only did somnivores not <em>need</em> to harm their prey, they also held no desire to. Sleepy and docile, these little creatures seemed to have a completely different set of priorities than their ancestors.</p>
<p>One such priority was fulfilling their latent instinct to build a community, a colony. Perhaps it&#39;s due to their origins, which remain a powerful testament to the power of unity - even today. Over the next handful of decades, somnivores worked to perfect their reproduction ritual and bolster their numbers, thoroughly depleting the backlog of soul prisms that the Alliance had amassed over time.</p>
<p>The town that once had no more than five of any single creature was now filled to the gills with the curious little dream eaters. Their creators were not forgotten, though - they lived their remaining days comfortably, the agile somnivores stealthily fetching the small amount of resources they still needed to live.</p>
<h1 id="-the-creation-of-reverie-"><strong>The Creation of Reverie</strong></h1>
<hr>
<p>Out of soul prisms and out of space, the first colony of somnivores had a conundrum to solve. Earth wasn’t a good place to expand due to the risks humanity could pose if they were discovered... And the Underworld provided space, but no dreams. Traveling through realms that lie <em>above</em> or <em>below</em> one another is challenging, and not viable for daily travel or regular food runs.</p>
<p>Somnivores decided to test the limits of their combined magical abilities, setting their sights on a <strong>brand new</strong> realm. One that would lie parallel and adjacent to Earth’s, maintaining easy access to their food source while also providing them with limitless room for expansion.</p>
<p>The remaining demons and ghouls of the Obsidian Nest worked together with somnivores to help them hone their realm hopping abilities, also showing them where and how to harvest more soul prisms during their lessons. In exchange, somnivores would continue to run “errands” for them, providing them with food and resources for the remainder of their natural lives.</p>
<p>Now confident in their knowledge of realm construction and travel, somnivores were ready to carry out the single most ambitious magical feat of their era. They pooled together their abilities, joining together in a “shared dream” with strength proportional to every bat’s combined intentions. With an offering of a small fortune’s worth of soul prisms and several other mana-rich materials, the rift’s opening crackled through the air and revealed the entrance to Reverie.</p>
<p>Reverie came from <em>very</em> humble beginnings - only a solitary, small floating island suspended in an endless sea of void. But it was home, and somnivores made quick work making it feel as such. The colony built their first town, and the edges of the island curiously expanded alongside them. It would seem Reverie grew larger <em>with</em> their population; the increasing number of magical minds passively encouraging the malleable null space to take shape. Somnivores quickly realized that they could make this happen <em>intentionally</em> by using their Shared Dream ability, and large expeditions formed to explore and expand the realm.</p>
<p>Today, Reverie is a bustling realm full of whimsy and mystery, lovingly crafted over generations by its curious inhabitants. The original rift still remains open, permanently linking Reverie and Earth at the center of the Obsidian Nest. The Nest still houses a handful of demons and somnivores, but now mainly serves as a massive hub for traders to exchange goods between Earth and Reverie.</p>
