AUTOGENERATED

<h1 id="-somnivore-physiology-magic-"><strong>🩺Somnivore Physiology &amp; Magic 🔮</strong></h1>
<h2 id="-how-somnivore-s-bodies-work-and-what-they-re-able-to-do-with-their-magic-"><em>How somnivore’s bodies work and what
    they’re able to do with their magic</em></h2>
<p>#</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left"><em>Section Summary</em> When a somnivore eats a dream that is palate-appropriate, it becomes
        fuel for their magic. This fuel is stored as cerebrospinal fluid, extending outward to make up their horns and wings. A
        somnivore’s magic is used for the following: Shapeshifting Flight Healing Sleepy Aura Reality Manipulation Reality
        Manipulation is made possible due to the magical properties of Reverie’s atmosphere. A single somnivore is able to alter
        reality in small ways. Includes telekinesis, apparitions, and invisibility. A group or colony of somnivores can combine
        their strength to execute a “Shared Dream” Used by the first colony to create Reverie. Used to expand / explore new
        regions.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>#</p>
<h1 id="-physiology-"><strong>Physiology</strong></h1>
<hr>
<h2 id="-consumption-resonance-"><strong>Consumption &amp; Resonance</strong></h2>
<p>When a somnivore consumes dream essence, their body reacts differently depending on whether the type of dream is able to be
  metabolized and stored in the body, a biological process commonly referred to as <strong>resonance</strong>. This system of
  resonance is what allows a somnivore’s body to turn dream essence into fuel for their magic - and also defines their palate in
  the process.</p>
<p>That magical fuel is processed by the body and then stored inside a somnivore’s <strong>cerebro-spinal fluid (CSF).</strong>
  This goopy, dream essence-filled fluid surrounds a somnivore’s brain and spinal cord and connects to their horns and wings,
  which are materialized using the unique substance. Besides being a striking part of their appearance, a somnivore’s
  essence-filled horns serve as extra storage to ensure that their brain is never allowed to dry out. This storage is incredibly
  dense, horn size doesn’t actually influence capacity in any significant way. The CSF that suspends and surrounds the brain
  serves as the conduit for their magical abilities; it’s the catalyst that transforms thoughts (imagination with intent) into
  actual magic.
  <strong>![][image1]</strong>
  Somnivores are normally only suited to absorb and metabolize one to two types of dream essence without taking on a number of
  detrimental symptoms. Having off-palate, unprocessed essence in their system can induce a number of side-effects such as
  light-headedness, nausea, fatigue, and more - increasing in potency with the amount they’ve consumed. In extreme cases of
  disproportionately off-palate diets, the bare-minimum amount of resonant essence stays preserved in their skull, tasked only
  with keeping their brain in good health, at the cost of all usable magic.
</p>
<p>Thankfully dreams are abundant in Reverie, and somnivores are able to thrive with a plethora of palate appropriate meals to
  choose from.</p>
<h2 id="-starvation-"><strong>Starvation</strong></h2>
<p>Thanks to the aforementioned dream abundance, starvation is never seen in Reverie. However, the condition remains an important
  cautionary tale for modern somnivores to learn.</p>
<p>When facing starvation a somnivore will begin to turn bestial. Their horns will darken, their wings will retract, and they will
  begin to lose their higher functions as they become increasingly hunger-driven. They lose the ability to transform or perform
  any sort of magic, and their eyes glaze over. Starvation alone is not enough to kill a somnivore, but it weakens them to the
  point where they can no longer heal major injuries, which could ultimately lead to their demise.</p>
<p>Somnivores facing starvation are usually found stranded in unpopulated areas of Earth, or in infernal places such as Limbo or
  the Underworld where creatures are unable to sleep or dream. A starving somnivore can be rehabilitated, but will lack any
  memories from the time they were starved. The sustained brain damage is able to be mended, but leaves the past a splotchy blur
  of only feelings and flashes of color.</p>
<p>![][image2]</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image3]</th>
      <th style="text-align:left">Leo Did you know? Early colonies used to <em>banish</em> bats to the Underworld if they committed
        an egregious enough crime. No creatures amongst the damned have the capacity to dream, so any somnivores stranded there
        would be doomed to starvation. A truly cruel fate! 😞 Thank goodness modern somnivores are not so <em>barbaric</em>. At
        least, I’m pretty sure we stopped doing that…</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<h2 id="-sleep-"><strong>Sleep</strong></h2>
<p>Somnivores have the ability to <em>sleep</em>, but lack the capacity to <em>dream</em>. Since they’re unable to enter a deep,
  REM-filled slumber, they tend to nap in short intervals through the daylight hours. They will still typically accumulate around
  a total of six to eight hours of rest each day (even if their sleepy demeanor may suggest otherwise).</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image4]</th>
      <th style="text-align:left">Rune They <em>saaaay</em> somnivores only <em>neeed</em> six hours of sleep, but I’m convinced
        that’s a lie spread by R.E.M. just to get bats to work longer shifts at their factories. I’ll be sleeping my required 11
        hours, thank you very much.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>##</p>
<h2 id="-aging-"><strong>Aging</strong></h2>
<p>Somnivores age at a rate that is comparable to humans until they reach full maturity around the age of <strong>twenty</strong>.
  As they move into adulthood, the rate at which they age slows dramatically. While they have <em>very</em> long lives, somnivores
  were unfortunately unable to inherit true immortality from their ancestors. Old age has taken a precious few of the somnivore
  population in recent decades, the oldest colony members passing away at around <strong>three hundred</strong> years of age -
  though some have still surpassed this.</p>
<p>Scholars speculate that immortality was lost as a byproduct of their soul prism-based creation. Recycling old soul fragments
  surely has its side effects, and they’re only just now becoming known as the species enters its fourth century of existence.</p>
<p>Immortality may not be a part of their default toolkit, but that certainly doesn’t stop a few very determined bats from doing
  everything in their power to try and obtain it.</p>
<h1 id="-magic-"><strong>Magic</strong></h1>
<hr>
<p>Magic is performed through <strong>intent and imagination</strong> - channeling a thought and materializing it through the
  power of the dream essence that surrounds their mind. Some feats are easier to achieve than others; basic magic abilities allow
  for changes to the self such as sprouting wings and shapeshifting, while more advanced techniques can be used to alter reality
  itself.</p>
<h2 id="-shapeshifting-"><strong>Shapeshifting</strong></h2>
<p>Somnivores are able to shapeshift into a humanoid version of themselves referred to as their “demon” form. This transformation
  functions similarly to how their vampire ancestors also once freely shifted between bat and humanoid bodies. Which form a
  somnivore favors depends on their personal preference, but bat forms are always used for traveling and hunting.</p>
<p>Shapeshifting requires a somnivore to have full control of their magic; perfecting and maintaining a demon form isn’t feasible
  until adulthood. Many young somnivores daydream about their demonic visage, taking inspiration from the dreams they consume. It
  isn’t uncommon for a somnivore to decide what their demon form will look like long before they’re even able to pull off the
  transformation. Having multiple different demon forms is also possible, though it does take practice and a certain level of
  skill.</p>
<p>##</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image5]</th>
      <th style="text-align:left">Esmerelda I was a real doll in my prime. I had a demon form fit to woo just about <em>any</em>
        pretty lil thang that caught my eye. Tall or petite, fit or curvy - I wore it all eff-ort-less-ly! <em>Nowadays</em>, I
        don’t mind looking my age one bit. I find it quite suits me. Wouldn’t you agree, Sonny? 😉✨ <em>NYEHEHE!!</em> Ahh, I’m
        just joshin’ ya. If ya ever need a hand perfecting that demon form o’ yours though, feel free to come to ol’ Esmerelda!
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>Switching forms consumes a bit of magic, but somnivores are able to do so freely with little to no “cooldown” between shifts.
  While not necessary, it is common courtesy to mask this transformation, be it with a <strong>flashy display of colors</strong>
  or a more <strong>subtle puff of smoke</strong>. This masking effect will always take on the same colors and appearance as a
  somnivore’s palate, as all visible magic does. A somnivore’s clothing and accessories are conveniently stored in their own
  suitcase-sized pocket dimension, ensuring they don’t get caught in the nude after swapping.
  ![][image6]</p>
<h2 id="-pocket-dimension-"><strong>Pocket Dimension</strong></h2>
<p>Literally putting the pocket in pocket dimension!</p>
<p>All somnivores possess access to an individual microfold in space due to their reality warping abilities. This pocket dimension
  is “suitcase sized” in its storage capacity and most often used for tools, personalized items, or clothes needed for
  transforming into their demon form. It allows for the containment of physical, non-sentient matter, but cannot sustain anything
  with an active mind. Sentient beings interfere with the mini-dimensional’s cohesion, making storage dangerous or impossible.</p>
<p>Just as using obscuring mist during transformation is traditional, so is creating a tangible &quot;anchor&quot; to personalize
  and stabilize access. Instead of simply snapping their fingers to store a phone, many prefer to slip it into a special conduit
  like a “pocket-dimension purse” or customized container that serves as an access point.</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image7]</th>
      <th style="text-align:left">Bunny My pocket dimension is always absolutely stuffed!! Gahh, I get sooo embarrassed when I
        have to walk through security and the dimension detector makes all my things pop out and clatter to the floor. Everyone is
        always like, super polite about it, but I can’t help but feel like they’re judging me for always keeping five different
        pairs of sunglasses in my pocket D. 😖</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>##</p>
<h2 id="-flight-"><strong>Flight</strong></h2>
<p>A somnivore’s wings are materialized using the dream essence they consume - it may take some practice to get the hang of
  navigating the air, but it&#39;s an ability all somnivores have. These wings are able to carry a somnivore’s body very long
  distances (regardless of their size) while only using a small amount of magical energy. Some flight fanatics are even able to
  expend extra magic for short bursts of blinding speeds!</p>
<p>While in their demon form, a somnivore may choose to materialize their wings as an aesthetic choice. They aren’t able to take
  flight, but can glide short distances if their wings are large enough.</p>
<p>##</p>
<h2 id="-healing-"><strong>Healing</strong></h2>
<p>Somnivores’ bodies passively use magic to heal most injuries and illnesses. Injuries that are able to be healed are mended
  quickly; about ten times faster than a human body would be able to.</p>
<p>Not all injuries are able to be healed, however - lost limbs are unable to grow back and broken horns or torn wings cannot mend
  on their own. Any injury that pierces their brain is fatal, as it is for most living beings.</p>
<p>![][image8]</p>
<p>##</p>
<h2 id="-sleepy-aura-"><strong>Sleepy Aura</strong></h2>
<p>The presence of a somnivore is almost always accompanied by a deep, dream-filled slumber. They passively emit a soothing aura
  that increases melatonin production - some swear it also smells faintly of lavender, though the scent varies from somni to
  somni. This ability developed as an evolutionary advantage, allowing somnivores to more consistently secure a quality meal while
  also decreasing the chances of a dreamer stirring awake mid-feeding.</p>
<p>Beings that reside in Reverie full time thankfully develop a tolerance to this effect, allowing them to live among somnivores
  without constant brain fog and sleeping spells.</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image3]</th>
      <th style="text-align:left">Leo <em>[Leo leans in, as if telling you a secret]</em> My soothing aura carries the scents of
        cedarwood, leather bound tomes, and aurosas, by the way. Intoxicating, is it not? 🌹💕😘</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image9]</th>
      <th style="text-align:left">Gala Leo, I’m pretty sure that’s just your regular cologne. 🙄</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>##</p>
<h2 id="-reality-manipulation-"><strong>Reality Manipulation</strong></h2>
<p>Dream magic has reality-altering properties, especially in Reverie’s mana-rich atmosphere. All of a somnivore’s most impressive
  magical powers fall under this “reality manipulation” umbrella.</p>
<p>A single somnivore is able to perform small feats of reality manipulation on their own, such as light telekinesis or creating
  wispy apparitions. Invisibility can also be achieved by altering the air around them, but it requires unwavering focus to
  maintain. Mastery of invisibility is required to obtain a Dream Hunter’s License (along with other skills such as flight
  maneuverability and portal channeling).</p>
<p>Large-scale reality manipulation can be orchestrated by a group or <em>colony</em> of somnivores - this is referred to as a
  “Shared Dream”. This magic scales with the number of users, growing stronger each time the intent of the incantation is
  reinforced by another somnivore.</p>
<p>The original colony of somnivores used this power to create the first rift into Reverie. This method is also used to explore
  and expand new areas of Reverie; the landscape taking shape as a median of the group’s envisioned formation. On a smaller scale,
  teams of builders are able to use shared dreams to efficiently transform raw materials into Reverie’s various structures. A
  blueprint and exact materials are needed - using only imagination and estimations would be far too unstable for creating sound
  structures built to last.</p>
