AUTOGENERATED

<h1 id="-somnivore-lifecycle-education-"><strong>🌱 Somnivore Lifecycle &amp; Education 📚</strong></h1>
<h2 id="-birth-childhood-schooling-and-a-veeery-long-adult-life-"><em>Birth, childhood, schooling, and a veeery long adult
    life</em></h2>
<p>#</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left"><em>Section Summary</em> Somnivores don’t reproduce sexually, instead incubating soul prisms to
        create new somnivores. Soul prisms only need a steady supply of harmonious energy to develop, allowing all sorts of
        couples and dynamics to bring a baby somnivore pup into the world. Young somnivores attend Reverie’s boarding school,
        Reverie Academy, from ages 10-20. Somnivores are fully mature at 20 years of age. Their palate has been cemented Able to
        use magic Includes being able to materialize their wings, fly, and shapeshift into their demon form. Somnivores have a
        natural lifespan of around 300 years.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>#</p>
<h1 id="-reproduction-"><strong>Reproduction</strong></h1>
<hr>
<h2 id="-origins-"><strong>Origins</strong></h2>
<p>Somnivores evolved artificially, brought into the world by the desperate experiments of the <a
    href="?tab=t.n0x0zhintecy"><strong>Infernal Alliance</strong></a>. The main catalyst used for this evolution is called a
  <strong>soul prism</strong>; an arcane artifact smuggled from the underworld that contains pieces of fragmented souls. These
  pieces can be forged together to create a new life - the process that eventually gave rise to the dream-feeding hybrid species.
</p>
<p>Somnivores carry a complex heritage that combines the essence of multiple supernatural beings. Due to this hybrid nature, they
  are incapable of natural genetic reproduction or ‘turning’ others like their vampiric ancestors. Instead, they carry out a
  reproduction <strong>ritual</strong> that uses soul prisms, not unlike the process their ancestors went through to bring them
  into existence. This ritual has been refined through the generations, now a celebration of love and life instead of a desperate
  bid at survival.</p>
<p>Today, Reverie maintains formal trade routes and agreements with the demons of the Underworld to retain their access to soul
  prisms. Sanctioned expeditioners make the perilous journey into the depths of the Underworld once per year to secure this
  precious resource.</p>
<p>![][image1]</p>
<h2 id="-soul-prisms-"><strong>Soul Prisms</strong></h2>
<p>The natural state of a soul prism is volatile, fragile, and vaguely sinister. The fragmented soul pieces carry countless years
  of anguish and suffering experienced during their time in the Underworld - enough to finally reach their breaking point. These
  pieces aren’t sentient, but they remain incredibly receptive to <strong>energy</strong>.</p>
<p>With exposure to enough affectionate and harmonious energy, a soul prism’s inner disarray will fade away. The fragmented bits
  of souls are soothed by the warmth of a loving home, finally able to rest. Only then are they able to meld together and become
  the precious essence used to create a new life.</p>
<p>Once development is underway, the prism will softly glow and become warm to the touch as the somnivore inside begins to form.
  There is no linear timeline for when a newborn will crack out of its prism. It happens when the crystal has become brittle, all
  of its strength now belonging to the new life within. The frail outer shell will crack and fall away to reveal a tiny newborn
  somnivore pup!</p>
<h2 id="-ritual-"><strong>Ritual</strong></h2>
<p>While it’s called a ritual, there isn’t really a whole lot that needs to actually be <em>done</em> by the somnivores. It’s just
  like incubating an egg, but the growth is generated by love instead of heat.</p>
<p>The prism is nestled into a handcrafted nest and placed in the heart of the home. This nest is constructed out of materials and
  items that carry <strong>sentimental value</strong>, helping jumpstart the prism’s cleanse. It’s also crucial that the nest
  contains genetic material from two parents - this is usually fur, since it’s soft and looks much nicer than the alternatives.
</p>
<p>All sorts of pairs can foster a soul prism - whether their relationship is platonic or romantic. Polyamorous or communal
  households may also carry out the ritual, though the offspring will ultimately only pull genetic influence from the two members
  that constructed the nest - introducing any extra “parents” increases the risk of an unsuccessful soul formation.</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image2]</th>
      <th style="text-align:left">Rune Look - I’m not looking to have a pup of my own just yet, but can we all agree that I would
        absolutely <em>crush</em> that nest build? Quilts, plushies, cushions… tiny vinyl figures, shiny glass beads, ribbons and
        scrunchies aplenty… AND my super duper soft and luxurious fluff to tie it all together? <em>[Rune makes a ‘chef’s kiss’
          motion]</em></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>#</p>
<h1 id="-lifecycle-"><strong>Lifecycle</strong></h1>
<hr>
<h2 id="-image3-"><strong>![][image3]</strong></h2>
<h2 id="-age-ranges-"><strong>Age Ranges</strong></h2>
<ul>
  <li>Pup: Ages 0-2</li>
  <li>Fledgling: Ages 2-11</li>
  <li>Adolescent: Ages 12-19</li>
  <li>Adult: 20-300</li>
</ul>
<h2 id="-pups-"><strong>Pups</strong></h2>
<p>Pups are just teeny tiny babies. They crawl around on all 4 paws. Their ears are a bit rounded and floppy and their tail is
  stubby and tuftless. Somnivore pups have no horns or wings, only tiny horn nubs that are just starting to show. Pups have a diet
  of only mundane dreams that have been diluted with fresh spring water.</p>
<p>##</p>
<h2 id="-fledglings-"><strong>Fledglings</strong></h2>
<p>Fledglings are the somnivore equivalent to human children. At this stage they’re still plump with their baby fat and are
  learning to walk on two legs. Their ears are a bit larger and pointier, their nubs have fully developed, and they’ll begin to
  grow a tuft of fur on the tip of their tail. Fledglings still have no horns or wings at this stage, and still follow a strict
  diet of only mundane dreams.</p>
<p>##</p>
<h2 id="-adolescents-"><strong>Adolescents</strong></h2>
<p>Somnivores really begin to come into their own during the adolescent stage. Their bodies are similar to an adult’s in shape,
  only slightly smaller in size. They’re mature enough to begin trying different types of dreams, though they are diluted to ease
  the transition. As they discover which dreams resonate with them, their horns slowly begin to form around their nubs. These
  horns are always small at first, and the colors inside are dull and may fluctuate as they discover which palate best suits them.
  Due to the transient nature of their palate during this stage, adolescent somnivores are still unable to use magic and remain
  wingless.</p>
<p>##</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image4]</th>
      <th style="text-align:left">Gala Hehe, get this! When we were kids, Bunny had an honest to god <em>emo phase</em>. They
        wanted to be a dreadful somnivore SOOO badly. They ate so many nightmares even though the palate never clicked, poor thing
        almost always had a tummy ache. 😥</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image5]</th>
      <th style="text-align:left">Bunny Galaaa!!! Nooo, you know I hate this story! … I did make an <em>adorable</em> emo kid
        though. I still have my Boobun hoodie somewhere! Honestly though, I’m thankful dreadful dreams never resonated with me.
        Strange and energetic ones are just so much more fun! They always get me pumped up and ready to tackle the day! 👊</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<h2 id="-adults-"><strong>Adults</strong></h2>
<p>Somnivores reach full physical maturity around 18-20 years old. At this age, their palate has been fully cemented and does not
  (naturally) change over the course of the rest of their life, except in extenuating circumstances.</p>
<p>Now with full agency of their magic, mature somnivores are able to sprout wings, fly, and shapeshift into their demon form at
  will. They’re able to perform other kinds of magic as well, which can be explored in the <a href="?tab=t.cbp40x5udqni">Somnivore
    Physiology &amp; Magic</a> section!</p>
<p>#</p>
<h1 id="-early-development-education-"><strong>Early Development &amp; Education</strong></h1>
<hr>
<h2 id="-it-takes-a-colony-"><strong>It Takes a Colony</strong></h2>
<p>Somnivores have a strong sense of community, much like real world bat colonies do. Parents often share the responsibilities of
  raising pups with the members of their neighborhood. Parents often take turns watching over multiple pups, and sometimes pupless
  somnivores enjoy helping as a change of pace. This allows parents a much needed reprieve, and allows pups to have a healthy
  diversification in their socialization.</p>
<p>Even though pups might spend time under several different roofs, they always have a warm meal and bed waiting for them at their
  parents’ home.</p>
<h2 id="-daycare-"><strong>Daycare</strong></h2>
<p>Daycare is also an option for young somnivores, providing them with a safe space to play and socialize with their peers. These
  spaces are full of fun and colorful sensory toys and imaginative playsets for playing pretend.</p>
<h2 id="-schoolhouses-"><strong>Schoolhouses</strong></h2>
<p>At age 6, all somnivores must be enrolled at the closest school house, which they attend 4 days a week until they turn 10.
  These schools shallowly cover a wide variety of topics, mainly serving as a place to foster curiosity and desire for knowledge.
  Some believe it&#39;s more of a glorified daycare than an educational institution, but many somnivores look back at these years
  fondly.</p>
<p>##</p>
<h1 id="-reverie-academy-"><strong>Reverie Academy</strong></h1>
<hr>
<p>At age 10, somnivores are whisked away to Reverie Academy; a whimsical boarding school where they begin learning a proper
  curriculum. After enrollment, students spend the next decade learning everything from the art of magic, history of the world,
  and the important tasks of everyday life.</p>
<p>Even though students live in campus dorms, there are plenty of holidays and extended weekends throughout the year when they’re
  able to return home and visit with family and friends.</p>
<h2 id="-grades-1-3-age-10-13-"><strong>Grades 1 - 3 (Age 10 - 13)</strong></h2>
<p>These grades establish many classical subjects, including math, literature, art, science (&amp; magic), and history. Somnivores
  continue learning all of these subjects at higher levels in later grades, but these years establish the basics.</p>
<p>Socially, somnivores are encouraged to participate in at least one of the many clubs and extracurriculars that Reverie Academy
  offers. Some examples include the Crafter’s Colony, the Grub Club, and the Somnivore-Human Alliance (SHA).</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image6]</th>
      <th style="text-align:left">Leo Getting to teach history for the little fledglings is always such a treat! Many have <em>no
          idea</em> how somnivores came to be prior to my course, outside of some very “creative” bedtime stories that their
        parents may have told them. I always get a hardy chuckle when I tell them about the Soul Prism Experiments - their faces
        either drain of color or light up with delight! It’s a good indicator for which little ones in the bunch will wind up
        favoring dreadful or strange dreams. 😊</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<h2 id="-grades-4-7-age-14-17-"><strong>Grades 4 - 7 (Age 14 - 17)</strong></h2>
<p>These grades introduce more nuanced topics that delve into how somnivores function and navigate the world.</p>
<p><em>Courses include:</em></p>
<p><strong>Dream Chemistry</strong></p>
<ul>
  <li>Teaches somnivores how to identify the different types of dreams and how R.E.M sleep operates. Understanding how dream types
    are distinguished and the human emotions that define them is a crucial stepping stone in discovering their palate.</li>
</ul>
<p><strong>Biology &amp; Health</strong></p>
<ul>
  <li>Covers how somnivore bodies function, the importance of resonance and a healthy diet, and all about their lifecycle.</li>
</ul>
<p><strong>Magical Theory</strong></p>
<ul>
  <li>Teaches about different ways dream magic can be used. While somnivores are unable to actually <em>practice</em> magic at
    this age, it’s crucial that they have a thorough understanding before wielding it in adulthood.</li>
</ul>
<p><strong>Earth Education</strong></p>
<ul>
  <li>Educates somnivores about the differences between Reverie and Earth, and all of its dangers. This course covers dream
    collection methods and outlines the strict safety measures that are in place for Earth travel.</li>
  <li>Includes a somnivore’s first <strong>field trip to Earth</strong>! They spend three days visiting an allied witch coven’s
    commune. This also includes a stealthy visit to a major human city (with the help of flight and invisibility administered by
    experts).</li>
</ul>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image4]</th>
      <th style="text-align:left">Gala I still remember my 6th grade Earth trip! It was absolutely <em>fascinating</em>. I love
        experiencing new places, and Earth was unlike anything I had ever seen! The witches were all suuuper nice, too! They used
        their polymorph forms to make us more comfy and oh my GOSH were they just the cutest! The beach left me a little
        disappointed though. It was hard to see much through the cloudy water. Lullabay definitely has Salem’s beaches beat, no
        doubt.✨</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p><strong>Brewing Basics</strong></p>
<ul>
  <li>An optional course for somnivores that express an interest in brewing dream potions and other magic-imbued concoctions.</li>
</ul>
<p><strong>Bug Catching, Foraging, &amp; Cookery</strong></p>
<ul>
  <li>An optional course that teaches somnivores about which plants and creatures native to Reverie are safe for consumption and
    how to properly prepare them!</li>
</ul>
<h2 id="-grades-8-10-ages-18-20-"><strong>Grades 8 - 10 (Ages 18 - 20)</strong></h2>
<p>Somnivores are able to take advanced courses for practical magic once their palate has fully cemented. This timeline varies
  since everyone reaches maturity at slightly different speeds, but is tracked by regularly monitoring a somni’s horn size and
  hue. When a somnivore’s horns haven’t changed for more than a month, it’s safe to say that their palate is finished cooking and
  they can begin learning magic!</p>
<p>#</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">First Feeding This milestone is marked with a somnivore’s very first live feeding; an important
        coming of age ceremony traditionally held in Lucid Valley. This ceremony requires several volunteers with the capacity to
        dream, relying on the non-somnivore residents of Reverie to step up for the occasion. Volunteers are provided with an
        opulent bed topped with a sheer canopy for privacy from the audience. In the darkness of the Witching Hours, the glow of
        the delicately forming dream essence illuminates the park with its vibrant colors. The somnivores of the hour flock to a
        dream that suits them, ducking behind the canopy and feasting on a fresh dream for the very first time.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p><em>Courses include:</em></p>
<p><strong>Flyer’s Ed’</strong></p>
<ul>
  <li>Teaches somnivores how to take flight and maneuver in the air.</li>
  <li>In the beginning, somnivores wear helmets and excessive padding to protect them from the numerous fumbling falls and
    crashes… Magitech imaging devices are confiscated to spare somnivores the humiliation of having their accidents immortalized.
  </li>
</ul>
<p><strong>Magic Lab</strong></p>
<ul>
  <li>Teaches somnivores how to perform various magical acts. The best way to learn is by doing!</li>
</ul>
<p><strong>Shapeshifting 101</strong></p>
<ul>
  <li>Walks somnivores through the logistics and process of shapeshifting into their demon form.</li>
  <li>Somnivores take time planning and designing their demon form.</li>
  <li>For the practical portion of the class, somnivores are paired with an individual mentor and given a private space for
    practicing. First transformations commonly go awry… it&#39;s important that a somnivore is given a non-judgemental space until
    they’re able to get it just right!</li>
</ul>
<h2 id="-graduation-"><strong>Graduation</strong></h2>
<p>After successfully honing the basics of magic, somnivores are allowed to (literally) spread their wings and soar into the next
  chapter of their life. Some may choose to pursue higher education at Somniversity, while others prefer to find a place of their
  own and some modest work that they enjoy. Whichever path a somnivore chooses, their Reverie Academy diploma proves that they’re
  ready to take it on!</p>
<p>##</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image7]</th>
      <th style="text-align:left">Headmaster Cirrus I admit, I cannot help but get emotional during this momentous occasion that I
        am privileged enough to orchestrate each year.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image6]</th>
      <th style="text-align:left">Leo <em>[In a hushed tone]</em> He cries… a lot. 😔</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>##</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image7]</th>
      <th style="text-align:left">Headmaster Cirrus <em>Ahem!</em> I am just… so <em>proud</em> of every single student that earns
        their Reverie Academy diploma. It is truly an honor to witness the next generation of somnivores venture boldly into our
        wonderful realm!</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
