AUTOGENERATED

<h1 id="-somnivore-culture-"><strong>🌟 Somnivore Culture 🌛</strong></h1>
<h2 id="-how-a-species-of-laid-back-bats-run-things-"><em>How a species of laid-back bats run things</em></h2>
<p>#</p>
<table>
<thead>
<tr>
<th style="text-align:left"><em>Section Summary</em>  Somnivores value community &amp; leisure. Relying on one another means less work and more relaxation. Short work weeks, <em>many</em> holidays. Thriving scene for arts and culture thanks to their ample freetime.  Somnivores are sexless. However, somnivores may choose to represent human-inspired sex &amp; gender presentation however they prefer with their demon form. Relationships among somnivores are just as varied as they are among humans. Due to their long lives, somnivores are more likely to experience some level of fluidity in their relationships.</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left"></td>
</tr>
</tbody>
</table>
<p>#</p>
<h1 id="-colony-community-"><strong>Colony Community</strong></h1>
<h1 id="-">---</h1>
<p>Community is one of Reverie’s core values. Somnivores naturally form colonies; close knit groups that comfortably lean on one another for support. When everyone helps out, everyone can spend more time taking it easy - a somnivore’s favorite thing to do. As a result, residents of Reverie have a reputation for being largely helpful and kind.</p>
<h2 id="-events-"><strong>Events</strong></h2>
<p>The community celebrates <em>numerous</em> events and holidays throughout the year, to the point where it sometimes seems a bit excessive. Somnivores will truly take any excuse to unwind, party, and spend quality time with their friends and neighbors.</p>
<p>Reverie’s event planners always go all out, however silly the occasion may be. Each event is hosted in one of Reverie&#39;s major towns and cities, allowing coordinators  to completely transform the space into a spectacle tailored to the celebration’s theme (with extra accommodations for the influx of guests, if needed). These celebrations never fail to bring the whole realm together, also giving residents an excuse to travel and appreciate Reverie’s diverse landscape.</p>
<table>
<thead>
<tr>
<th style="text-align:left">![][image1]</th>
<th style="text-align:left">Millie Ooh I simply can’t wait for this year’s Fae Faire! 🦋 The way the forest clearing in Twilight Grove is decorated is always downright <em>magical</em>. So many floating lights, fancy ribbons, and tables full of tasty treats.  Of course the highlight for <em>me</em> is when all the forest critters come out to play! Every year I spot a few brand new little guys that I’ve never seen before - the Grove is such a mystifying place! 🥰</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left"></td>
</tr>
</tbody>
</table>
<h1 id="-work-leisure-"><strong>Work &amp; Leisure</strong></h1>
<hr>
<h2 id="-work-"><strong>Work</strong></h2>
<p>Somnivores have an extremely laid-back nature and greatly value their leisure time. Reverie’s society is structured in such a way that no one needs to work particularly hard to make ends meet; work weeks are four days and vacation time is plentiful. Gig work is also a common route, as there’s no shortage of odd jobs to be done around Reverie.</p>
<p>![][image2]</p>
<p>Admittedly, the realm has its fair share of unemployed residents that are welcome to lean on the community for support. Spending some time without being in schooling or a career is socially acceptable, and a period that many somnivores will go through at some point during their incredibly long adult life.</p>
<table>
<thead>
<tr>
<th style="text-align:left">![][image3]</th>
<th style="text-align:left">Rune I wish I had more Community Support available - they said 150 years was too long? And that I had to get some kind of <em>job</em> now? Ah, whatever. Whims and Wares is a chill place to work, I guess. And the more I see of that new girl that works in the back, the less I seem to mind clocking in…  <em>[Rune trails off, her cheeks flushing pink]</em></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left"></td>
</tr>
</tbody>
</table>
<h2 id="-leisure-"><strong>Leisure</strong></h2>
<p>Residents of Reverie are encouraged to use their down time to pursue passions, hobbies, or to simply kick back and relax. This generous allowance for recreation has contributed in no small part to Reverie’s thriving arts and culture scene.</p>
<h1 id="-identity-relationships-"><strong>Identity &amp; Relationships</strong></h1>
<hr>
<p>#</p>
<table>
<thead>
<tr>
<th style="text-align:left">Note: You’re free to use any real life identities/labels for your somnivores! This section’s purpose is to provide context for the culture surrounding sexuality &amp; relationships in Reverie, not to place restrictions on how you personally decide to characterize your OCs.</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left"></td>
</tr>
</tbody>
</table>
<p>#</p>
<h2 id="-sex-"><strong>Sex</strong></h2>
<p>Biologically, somnivores are sexless - they cannot reproduce sexually and thus have no sexual characteristics. In their demon form, somnivores may choose to represent human-inspired sex and gender according to their preference. These characteristics are fluid, and a somnivore may even have multiple demon forms that present differently in terms of gender, sex, and/or body type.</p>
<p>In any form, somnivores typically choose to define their preferred pronouns rather than prescribe to a specific gender identity, but this is ultimately a personal decision.</p>
<p>Much like humans, somnivores experience a wide variety of different attractions and desires in ways that are unique to each individual - there is no right or wrong way, and no stigmas towards different relationship styles in Reverie society.</p>
<h2 id="-relationships-"><strong>Relationships</strong></h2>
<p>Many somnivores desire romantic relationships with others; attending mixers, dating around, and even settling down with their perfect match. Given their long lives, somnivores often experience some level of fluidity in their relationship dynamics. Open relationships and polycules are common, though monogamous pairs aren’t unheard of.</p>
<p>Marriage isn’t an officially recognized status, but somnivores may use the terms husband, wife, or partner to denote a long term commitment. However, if things don’t work out, somnivores often opt for keeping breakups amicable over burning bridges due to the close knit nature of their community.</p>
<p>##</p>
<table>
<thead>
<tr>
<th style="text-align:left">![][image4]</th>
<th style="text-align:left">Esmerelda Get yer heart broken? I say BURN 👏 THAT 👏 BRIDGE 👏! Ain’t no spice a’ life if ya ain’t got enemies to spite! <em>NYEHEHEH!!</em> 🤣 Mosta my exes and I have mellowed with old age, though. Me an’ Cirrus go <em>waaaay</em> back. We spent half a century turning our snouts up at each other, but now we get drinks together every Wednesday night at The Sandman. I swear he’s the only bat in Reverie that can best me at yappin’. 🤣</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left"></td>
</tr>
</tbody>
</table>
