AUTOGENERATED

<h1 id="-reverie-tech-fashion-aesthetics-"><strong>🤳 Reverie Tech, Fashion, &amp; Aesthetics 🎀</strong></h1>
<h2 id="-transparent-plastic-flip-phones-and-never-getting-out-of-your-pajamas-what-more-could-you-want-"><em>Transparent plastic,
    flip phones, and never getting out of your pajamas - what more could you want?</em></h2>
<p>#</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left"><em>Section Summary</em> Somnivores heavily rely on magitech to make their lives easier.
        Reverie’s modern technology is powered by mana, a plentiful resource in Reverie. Device designs are inspired by the early
        2000s. Transparent Plastics Glowing Parts Fun Shapes &amp; Vivid Colors Magic pollution is an unfortunate byproduct of
        Reverie’s industrialization. Fashion is incredibly varied. Somnivores pull aesthetic inspiration from dreams. They
        prioritize whatever styles are the most comfortable to them. Pajamas &amp; Nightclothes are common wardrobe choices.
        Materials are high quality, soft, and luxurious. Somnivores love to accessorize their bat form, but don’t commonly wear
        full garments that could restrict their movement. Buildings look like they’ve been taken straight from dreams. Designs
        feature organic, rounded shapes and asymmetry. Bold and colorful. Built to accommodate Reverie’s diverse residents. Many
        towers, balconies, and high ceilings for bats.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<p>#</p>
<h1 id="-magitech-"><strong>Magitech</strong></h1>
<hr>
<h2 id="-energy-power-"><strong>Energy &amp; Power</strong></h2>
<p>Reverie’s magic-fueled electronics are collectively referred to as <strong>Magitech</strong>. Since mana is a versatile and
  plentiful resource in Reverie, it makes the perfect energy source to power all sorts of devices. Driven by their love of
  leisure, somnivores place a huge emphasis on innovation and automation, leaning heavily on magitech to make their lives easier.
</p>
<p>Devices are typically designed to be wireless, using chunky glowing batteries of highly concentrated mana to power them; you
  can actually see the amount of juice left through their transparent casing. Recent advancements in magictech even allow for
  low-power devices (like clocks, night lights, and e-readers) to run with no power source at all; instead passively absorbing
  mana from the air itself. High-power devices, however, may require a direct connection to a mana source via thick flexible PVC
  tubes, not unlike those used for water cooling inside PCs.</p>
<h2 id="-modern-advanced-technology-"><strong>Modern &amp; Advanced Technology</strong></h2>
<p>The technology itself is generally on-par with modern day Earth’s, though it lags behind and advances ahead in different areas.
  The internet landscape and personal device market are comparable to the early 2000s, while vehicles like scooters and trains can
  maneuver through the air freely in ways that humans have yet to perfect. Reverie’s engineers prioritize developing tech that’s
  <em>new</em> and <em>interesting</em> rather than making advancements in areas that they perceive as fulfilled - “if it ain’t
  broke, don’t fix it”.</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image1]</th>
      <th style="text-align:left">Rune Honestly? I could never live in a realm that doesn’t have the cybernet. Watching mewzy
        videos and scrolling through memes on Glimmr are load-bearing activities in my daily routine.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<h2 id="-aesthetic-"><strong>Aesthetic</strong></h2>
<p>Reverie’s tech is as colorful and varied as its residents. Inspired by the playful aesthetics of Earth’s 90s and 00s, magitech
  is designed with unique shapes, tactile buttons, and transparent plastics. Glowing parts are also common, either by using small
  lights or by directly displaying the mana that courses through the device. This soft glow not only <em>looks</em> cool, but also
  helps with visibility in low-light conditions.</p>
<p>Drop protection is also an important angle for somnivores to consider, as holding things with paws (especially while flying)
  can be tricky. Many devices come with lanyard/charm loops, or spots for attaching straps. Thick casing and rounded shapes also
  help with damage reduction; these delightfully clunky gadgets are built to last.</p>
<ul>
  <li><a href="https://www.pinterest.com/somnivores/technology/">https://www.pinterest.com/somnivores/technology/</a></li>
</ul>
<h1 id="-image2-"><strong>![][image2]</strong></h1>
<h2 id="-consequences-"><strong>Consequences</strong></h2>
<p>Despite its many conveniences, magitech isn&#39;t without its flaws. The process used to siphon mana from Reverie’s air and
  water takes massive, complex machines. Once the mana has been extracted, the contraption excretes mysterious smog and sludge -
  the colors seemingly changing at random, shimmering with an odd oil-slick finish. Its properties are unstable, and scientists
  are still studying what effects this magic pollution could have on Reverie’s environment and wildlife.</p>
<h1 id="-fashion-"><strong>Fashion</strong></h1>
<h1 id="-">---</h1>
<h2 id="-demon-form-"><strong>Demon Form</strong></h2>
<p>Pulling inspiration from the dreams they eat, somnivores have an extremely diverse fashion scene. Styles are limited only by
  imagination itself, spanning across all time periods and aesthetics.</p>
<p>One thing they never compromise on, however, is comfort. Somnivores typically value being comfortable above being trendy, and
  wearing pajamas or nightclothes out and about is commonplace. What a somnivore finds most comfortable varies based on the
  individual; some prefer being buried by layers while others favor wearing nothing more than their undergarments. Regardless of
  style, clothes are always made with high quality fabrics that evoke feelings of luxury and relaxation when brushing against
  their fur or skin.</p>
<ul>
  <li><a href="https://www.pinterest.com/somnivores/fashion/">https://www.pinterest.com/somnivores/fashion/</a></li>
</ul>
<table>
  <thead>
    <tr>
      <th style="text-align:left">![][image3]</th>
      <th style="text-align:left">Leo Oh, we’re discussing fabrics? Come here, you simply <em>must</em> try on my favorite
        overcoat. This heavy weave is nothing short of pure <em>luxury</em>, my dear✨And you do wear it quite nicely, if you don’t
        mind me saying so. 😉 Only the highest quality threads can shield my tender heart from the bone-chilling breeze of
        Grimhallow. This well-loved garment is made of 100% sheep sprite wool, and you’d be hard pressed to find anything cozier
        in all of Reverie!</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<h2 id="-bat-form-"><strong>Bat Form</strong></h2>
<p>It’s a common form of self expression for somnivores to accessorize in their bat form. Their large horns serve as a canvas to
  decorate with rings, charms, ribbons, and more! Pieces are also commonly worn around their tails, necks, and feet/ankles.
  Wearing full garments like tops, dresses, and pants is a bit less popular; it’s important that clothing doesn’t restrict their
  bodies for ease of flight and maneuverability.</p>
<p>![][image4]![][image5]</p>
<h1 id="-architecture-"><strong>Architecture</strong></h1>
<hr>
<p>Thanks to somnivores’ magic-aided construction methods, structures in Reverie are wholly unique and can be quite the spectacle.
  Resident architects love to utilize asymmetry, curved edges, and polychromy in their designs. Buildings are colorful and
  organic, like something plucked straight from a dream.</p>
<p>Many constructs are built with Reverie’s wide variety of residents in mind; accommodating for all sorts of shapes, sizes, and
  mobility levels. Large structures almost always include towers, landing balconies, and high vaulted ceilings for the ease of
  flying bat form somnivores.</p>
<p>Suburban and rural areas feature more humble architecture, though still with their own whimsical flare. Flourishes can be seen
  in their large windows, cozy balconies, and gabled roofs.</p>
<ul>
  <li><a
      href="https://www.pinterest.com/somnivores/reverie-architecture/">https://www.pinterest.com/somnivores/reverie-architecture/</a>
  </li>
</ul>
