AUTOGENERATED

<h1 id="-designing-somnivores-demon-form-"><strong>🎨 Designing Somnivores [Demon Form] 😈</strong></h1>
<p>![][image1]</p>
<p>##</p>
<h1 id="-overview-"><strong>Overview</strong></h1>
<h1 id="-">---</h1>
<table>
  <thead>
    <tr>
      <th>🌟Required Attributes that <em>always</em> translate from the bat form</th>
      <th>✨Optional Attributes that <em>can</em> translate from the bat form</th>
      <th>💫Fluid Attributes that are <em>not</em> tied to the bat form</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Horns Tail Skin Color Hair Color Ear size + angle Misc. Features (eye color, fangs) <strong>Required, if
          applicable</strong> Aura Traits Adornment Traits Material Traits on fur</td>
      <td>Wings Bat Ears Legs and Feet Nose Markings / Fur Paw pads and / or Claws <strong>Optional, if applicable</strong>
        Material Traits on skin</td>
      <td>Build / Height Gender Presentation</td>
    </tr>
  </tbody>
</table>
<p>![][image2]
  <strong>A somnivore can have up to three demon masterlist entries at any given time.</strong>
</p>
<p>Different demon forms can differ greatly from each other! They can express optional attributes differently (ex. one with wings
  and one without) and can f<strong>reely change their build/gender presentation</strong> since it’s not tied to their bat form.
</p>
<h1 id="-required-elements-"><strong>🌟Required Elements</strong></h1>
<hr>
<p><strong>Elements of a demon’s design that are always translated from their bat form.</strong>
  ![][image3]
  Examples of two demon forms that only possess the required traits.</p>
<h2 id="-horns-"><strong>🌟Horns</strong></h2>
<p>Same as their bat form. They must not change in relative size, angle, or placement.</p>
<h2 id="-tail-"><strong>🌟Tail</strong></h2>
<p>Same style as their bat form but the length scales with their height - typically ending around or just past their ankles.</p>
<p>Fur covering the <strong>thin</strong> part of a common somnivore’s tail is optional- it can be covered with skin or fur until
  it reaches the tip, or any gradient in-between</p>
<h2 id="-skin-color-"><strong>🌟Skin Color</strong></h2>
<p>A demon’s skin color must mirror the primary color of the bat form’s <strong>inner ear</strong>. Any skin color is possible,
  though cool colors tend to be the most common.
  ![][image4]</p>
<h2 id="-pointed-ears-"><strong>🌟Pointed Ears</strong></h2>
<p>By default, a demon’s ears are humanoid and pointed (elf-like) and match the angle &amp; sizing of their bat form.
  ![][image5]</p>
<h2 id="-hair-color-"><strong>🌟Hair Color</strong></h2>
<p>A demon’s hair color reflects the fur color(s) of their bat form.</p>
<p>The main (root) color of the hair must correspond with the fur <strong>on top of a somnivore’s head</strong>, or the
  <strong>tuft of fur on their forehead</strong> if they have one.</p>
<p>Accent colors can be added based on other colors present in a somnivore’s coat, but aren’t required.</p>
<p><em>![][image6]</em>
  📋Due to the nature of a somnivore’s shapeshifting ability, cosmetic changes like hair dye would not persist between form
  changes. If a somnivore wants to sport a different hair color, they would instead get the color of their bat form’s coat
  altered!</p>
<p>#</p>
<h1 id="-optional-elements-"><strong>✨Optional Elements</strong></h1>
<hr>
<p><strong>These can be included to add more elements that harken back to the bat form’s original design.</strong>
  <strong>Mix and match these as desired!</strong>
  ![][image7]
  Examples of two demon forms that possess required &amp; optional traits.
</p>
<h2 id="-bat-ears-"><strong>✨Bat Ears</strong></h2>
<p>Bat ears are taken directly from a demon’s bat form. These ears always <strong>connect on the sides of the head</strong> where
  a human’s ears would be regardless of their placement on the bat’s head.</p>
<p>Floppy bat ears may not be longer than a demon’s waist.</p>
<p>![][image8]</p>
<h2 id="-bat-nose-"><strong>✨Bat Nose</strong></h2>
<p>Demons with bat noses possess a <strong>wide and flat nose bridge</strong>, ending with a wet nose tip that mirror’s their bat
  form’s.</p>
<p>A bat nose is always accompanied by <strong>facial fur</strong>, which covers the forehead and nose bridge.</p>
<p>![][image9]</p>
<p>![][image10]
  Nose anatomy / Side-view</p>
<h2 id="-wings-"><strong>✨Wings</strong></h2>
<p>Must be the same shape as in their bat form, but placement and size may vary. Wings can be detached (hovering behind the torso)
  or attached to the lower or upper back.</p>
<p>Wings cannot be larger than a demon’s torso.</p>
<p>![][image11]</p>
<p>#</p>
<table>
  <thead>
    <tr>
      <th style="text-align:left">📋 Somnivores only materialize wings for aesthetics in their demon form - they cannot fly.
        However, if their wings are attached to their body and large enough, they are able to glide short distances.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:left"></td>
    </tr>
  </tbody>
</table>
<h2 id="-digitigrade-legs-"><strong>✨Digitigrade Legs</strong></h2>
<p>A demon form can have <strong>humanoid or digitigrade legs</strong>.</p>
<p>If a somnivore has digitigrade legs, the foot type must match their bat form and a <strong>fur gradient</strong> is required.
  This gradient can end anywhere above the ankle depending on fur coverage preferences</p>
<p>![][image12]</p>
<p>Digitigrade legs have lots of options for accessorizing!</p>
<p>Pawed feet are able to wear socks and shoes outfitted for digitigrade legs. However, hooved or clawed feet must <strong>keep
    the hooves/claws exposed</strong> and not completely covered by a sock or shoe.</p>
<p>![][image13]</p>
<h2 id="-paw-pads-claws-"><strong>✨Paw Pads &amp; Claws</strong></h2>
<p>Demons can have paw pads that match their bat form’s.</p>
<p>If a somnivore’s bat form has <strong>clawed upper paws</strong> then the demon form may possess clawed fingers. These are
  different from regular nails - claws are more talon-like and are (optionally) able to blend seamlessly with the fingertips.</p>
<p>![][image14]</p>
<h2 id="-markings-"><strong>✨Markings</strong></h2>
<p>Markings may be translated from their bat form onto their demon form. These don’t need to be 1:1 and can have changes that
  would make sense with the change in scale.</p>
<p>Demons can also have tattoos/markings that are not present on their bat form.</p>
<p>Markings and tattoos can cover up to 50% of a somnivore’s body.</p>
<p>![][image15]</p>
<h2 id="-limb-gradients-"><strong>✨Limb Gradients</strong></h2>
<p>Somnivores may have gradients covering up to 3/4ths of their limbs - this gradient color should correspond to the color(s) on
  their bat form.
  ![][image16]</p>
<h2 id="-fur-coverage-"><strong>✨Fur Coverage</strong></h2>
<p>At minimum, <strong>fur is required for any anatomy that has been translated from a somnivore’s bat form.</strong>
  The transition from skin to fur can be a gradient or drawn with a fur edge.</p>
<ul>
  <li>This includes bat ears, bat nose, digitigrade legs, and claws</li>
</ul>
<p>Fur coverage beyond this is allowed, the only restrictions being that skin must remain visible on the lower half of the face*,
  a small area of the chest, and the palms of the hand.
  <em>![][image17]</em>
  <em>\</em>Beards are allowed and would have the same coverage as on a human face.*
</p>
<p>#</p>
<p>#</p>
<h1 id="-mystic-seasonal-traits-"><strong>💫Mystic &amp; Seasonal Traits</strong></h1>
<hr>
<p>How traits translate to a somnivore’s demon form is dependent on the type of trait and sometimes even the specific trait
  itself. <strong>Refer to the descriptions on the <a href="?tab=t.h85kwmervxtp">mystic traits page</a> to see the
    specifications</strong> of how each one is able to translate between forms.</p>
<p><strong>As a general rule; Any part of a demon that has fur coverage will express traits in the same way as their bat
    form.</strong></p>
<h2 id="-material-traits-"><strong>💫Material Traits</strong></h2>
<h3 id="-change-or-alter-the-materials-of-a-somnivore-s-body-"><em>Change or alter the materials of a somnivore’s body</em></h3>
<hr>
<p>Some material traits only translate on fur (i.e. clouds), while others can be present on skin as well (i.e. glass).</p>
<h2 id="-adornment-traits-"><strong>💫Adornment Traits</strong></h2>
<h3 id="-add-things-to-a-somnivore-s-body-"><em>Add things to a somnivore’s body</em></h3>
<hr>
<p>Adornment traits commonly translate their number and location directly from the bat form regardless of the presence of skin or
  fur (i.e. extra eyes, extra wings).</p>
<h2 id="-aura-traits-"><strong>💫Aura Traits</strong></h2>
<h3 id="-modify-the-area-around-a-somnivore-"><em>Modify the area around a somnivore</em></h3>
<hr>
<p>Aura traits always translate; though some are more flexible in how they’re represented (i.e. stars around a somnivore can be in
  the same general area and don’t necessarily need to have the exact same amount as the bat form).</p>
<h1 id="-limitations-"><strong>Limitations!</strong></h1>
<hr>
<p>Limitations in place for all demon forms.
  <strong>💫 Proportions</strong>
  Demons are similar in build to humans, but their adult heights can range from <strong>3’6” to 8’</strong> [106cm to 243cm ]
</p>
<p><strong>💫 Age</strong>
  All somnivores on the masterlist are adults. They can be petite or short but cannot appear to be a child. The canonical age of
  your somnivore can range from 20 to 300 years old.</p>
<h1 id="-design-examples-"><strong>Design Examples</strong></h1>
<hr>
<p>Some somnivore NPCs with their demon form’s features broken down,
  just as some examples of different applications!</p>
<table>
  <thead>
    <tr>
      <th style="text-align:center">![][image18]</th>
      <th>Caspian’s demon form features: Bat ears Bat nose Claw fingertips Digitigrade legs (hooves) Wings connected to his lower
        back Extra Fur coverage (neck/shoulders)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:center"></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th style="text-align:center">![][image19]</th>
      <th>Gala’s demon form features: Pointed ears Plantigrade legs Skin markings (white freckles) Limb gradients on her legs
        Wings connected to her lower back</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:center"></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th style="text-align:center">![][image20]</th>
      <th>Millie’s demon form features: Bat ears Plantigrade legs No wings Markings as skin color (spots) Limb gradients on her
        arms</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:center"></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th style="text-align:center">![][image21]</th>
      <th>Rune’s demon form features: Elf ears (though obscured by her hair) Digitigrade legs (paws) Detached wings</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="text-align:center"></td>
    </tr>
  </tbody>
</table>
