<?php

return [
  '???'                      => '???',
  'Acquaintance'             => 'Acquaintance',
  'Best Friends'             => 'Best Friends',
  'Boss and Employee'        => 'Boss and Employee',
  'Co-workers'               => 'Co-workers',
  'Crushing'                 => 'Crushing',
  'Enemy'                    => 'Enemy',
  'Family'                   => 'Family',
  'Friends'                  => 'Friends',
  'Frenemies'                => 'Frenemies',
  'It\'s Complicated'        => 'It\'s Complicated',
  'Life Partners'            => 'Life Partners',
  'On-and-Off'               => 'On-and-Off',
  'Partners in Crime'        => 'Partners in Crime',
  'Past Relationship'        => 'Past Relationship',
  'Polyamorous Relationship' => 'Polyamorous Relationship',
  'Rival'                    => 'Rival',
  'Roommate'                 => 'Roommate',
  'Significant Others'        => 'Significant Others',
  'Student'                  => 'Student',
  'Mentor'                   => 'Mentor',
  'Teacher'                  => 'Teacher',
];
